# Generated by Django 5.1.1 on 2025-01-16 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='moisture',
        ),
    ]
