# Generated by Django 5.1.1 on 2025-01-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherproject', '0002_remove_weatherdata_moisture'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('pressure', models.FloatField()),
                ('altitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('current', 'Current'), ('past', 'Past')], default='current', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='WeatherData',
        ),
    ]
